#!/usr/bin/env bash
# Copyright (C) 2024 Iman moghadari

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Get the local IP address from the modem (local network)

if command -v ip &> /dev/null; then
    LIP=$(ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '127.0.0.1' | head -n 1)
elif command -v ifconfig &> /dev/null; then
    LIP=$(ifconfig | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '127.0.0.1' | head -n 1)
else
    echo "Neither 'ip' nor 'ifconfig' command is available."
    exit 1
fi

local_ip_icon() {
    echo "🏠"
}

echo "$LIP $(local_ip_icon)"
